apiVersion: v1
kind: Pod
metadata:
  name: pending-demo
spec:
  containers:
    - name: app
      image: nginx
      resources:
        requests:
          # Unrealistic CPU request causes scheduler failure
          cpu: "10"