apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readiness-demo
  template:
    metadata:
      labels:
        app: readiness-demo
    spec:
      containers:
        - name: app
          image: nginx
          readinessProbe:
            httpGet:
              # Endpoint does not exist → pod never becomes ready
              path: /health
              port: 80